### ISSUE TITLE
SMAPI installer 3.7.6.8 with 1.4.5.151 crash

### ISSUE THREAD

**Issue by TrxpOn13** [ZaneYork/SMAPI-Android-Installer#102]
Here is the summary : 

java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.zane.stardewvalley-rPa5z2lkM6pRDTPKVOO00w==/base.apk"],nativeLibraryDirectories=[/data/app/com.zane.stardewvalley-rPa5z2lkM6pRDTPKVOO00w==/lib/arm64, /data/app/com.zane.stardewvalley-rPa5z2lkM6pRDTPKVOO00w==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]] couldn't find "libmonosgen-2.0.so"
	at java.lang.Runtime.loadLibrary0(Runtime.java:1067)
	at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
	at java.lang.System.loadLibrary(System.java:1667)
	at mono.MonoPackageManager.LoadApplication(MonoPackageManager.java:86)
	at mono.MonoRuntimeProvider.attachInfo(MonoRuntimeProvider.java:35)
	at android.app.ActivityThread.installProvider(ActivityThread.java:7189)
	at android.app.ActivityThread.installContentProviders(ActivityThread.java:6672)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6567)
	at android.app.ActivityThread.access$1400(ActivityThread.java:224)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1887)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7562)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

Device : Pocophone F1
RAM : 4GB

**Comment by ZaneYork** [comment]
Could you please send your patched apk and origin SDV apk file?

**Comment by Mariaeduardaconrado** [comment]
Não consigo baixa fica dando erro toda hora como eu faço pra resolver isso
