### ISSUE TITLE
Smapi Stardew valley keeps crashing

### ISSUE THREAD

**Issue by Justm315** [ZaneYork/SMAPI-Android-Installer#134]
Sv version is 1.4.5.150
![Screenshot_2021-04-11-09-53-24-460_com miui home](https://user-images.githubusercontent.com/82297250/114289592-caf3ea00-9aab-11eb-9643-533622adc4e5.jpg)
Smapi installer is v3.7.6.9
Here's the report :
java.lang.RuntimeException: Unable to instantiate application ru.androeed.utilsfacebookinstagramm.AppApplication: java.lang.ClassNotFoundException: Didn't find class "ru.androeed.utilsfacebookinstagramm.AppApplication" on path: DexPathList[[zip file "/data/app/com.zane.stardewvalley-PwHK21BRFqhNzxoOE2fzRQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.zane.stardewvalley-PwHK21BRFqhNzxoOE2fzRQ==/lib/arm64, /data/app/com.zane.stardewvalley-PwHK21BRFqhNzxoOE2fzRQ==/base.apk!/lib/arm64-v8a, /system/lib64, /product/lib64]]
	at android.app.LoadedApk.makeApplication(LoadedApk.java:1230)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6553)
	at android.app.ActivityThread.access$1400(ActivityThread.java:224)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1887)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7562)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
Caused by: java.lang.ClassNotFoundException: Didn't find class "ru.androeed.utilsfacebookinstagramm.AppApplication" on path: DexPathList[[zip file "/data/app/com.zane.stardewvalley-PwHK21BRFqhNzxoOE2fzRQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.zane.stardewvalley-PwHK21BRFqhNzxoOE2fzRQ==/lib/arm64, /data/app/com.zane.stardewvalley-PwHK21BRFqhNzxoOE2fzRQ==/base.apk!/lib/arm64-v8a, /system/lib64, /product/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at android.app.AppComponentFactory.instantiateApplication(AppComponentFactory.java:76)
	at android.app.Instrumentation.newApplication(Instrumentation.java:1156)
	at android.app.LoadedApk.makeApplication(LoadedApk.java:1222)
	... 9 more

**Comment by ZaneYork** [comment]
ru.androeed.utilsfacebookinstagramm.AppApplication is definitely not a piece of the SMAPI of Android platform, make sure your OS environment is pure and clean
