### ISSUE TITLE
cannot start last version

### ISSUE THREAD

**Issue by burunduk** [ZaneYork/SMAPI-Android-Installer#170]
Install stardewvalley версія 1.4.5.151
Install smapi last release.
Install smapi stardewvalley
Run, and have in catlog:

`FATAL EXCEPTION: main
Process: com.zane.stardewvalley, PID: 10854
java.lang.UnsatisfiedLinkError: dlopen failed: library "libmonosgen-2.0.so" not found
	at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
	at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
	at java.lang.System.loadLibrary(System.java:1664)
	at mono.MonoPackageManager.LoadApplication(MonoPackageManager.java:86)
	at mono.MonoRuntimeProvider.attachInfo(MonoRuntimeProvider.java:35)
	at android.app.ActivityThread.installProvider(ActivityThread.java:7246)
	at android.app.ActivityThread.installContentProviders(ActivityThread.java:6787)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6704)
	at android.app.ActivityThread.access$1300(ActivityThread.java:237)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7664)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)`

**Comment by burunduk** [comment]
libmonosgen not present in original sdw apk.
