### ISSUE TITLE
Installed but not running

### ISSUE THREAD

**Issue by FansaiKudosai** [ZaneYork/SMAPI-Android-Installer#216]
The game installs but won't launch.  Android 12, miui 13. Gives an error message
java.lang.UnsatisfiedLinkError: dlopen failed: library "libmonosgen-2.0.so" not found
	at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
	at java.lang.Runtime.loadLibrary0(Runtime.java:998)
	at java.lang.System.loadLibrary(System.java:1656)
	at mono.MonoPackageManager.LoadApplication(MonoPackageManager.java:86)
	at mono.MonoRuntimeProvider.attachInfo(MonoRuntimeProvider.java:35)
	at android.app.ActivityThread.installProvider(ActivityThread.java:7717)
	at android.app.ActivityThread.installContentProviders(ActivityThread.java:7234)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6959)
	at android.app.ActivityThread.access$1600(ActivityThread.java:265)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2103)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8166)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1037)

**Comment by Cxxton** [comment]
It keeps saying that I couldn't install it! The smapi installer is installed but it won't work! Everytime I press 'install" it keeps failing
