### ISSUE TITLE
No Android 13 support.

### ISSUE THREAD

**Issue by nick123456789025** [ZaneYork/SMAPI-Android-Installer#233]
On Android 13, Google has imposed restrictions on file access (SAF), this is preventing the app from working properly. The installer will try to prompt SAF but The user cannot give access to that folder anymore, and it is not possible to select a different folder or the game directory. 

![Screenshot_20220831-181558](https://user-images.githubusercontent.com/55955972/187795017-7a8a0e46-6996-446a-bbad-a80a6f703260.png)

 There is a workaround. you can install the app on an Android 9-12 device, and then copy the files over to the device you want to run the game, Install the APK from the SMAPI installer folder.

A possible fix would be to update the path that the framework is looking for when the app prompts it, change it so it is looking for the games directory or whatever directory that the app is currently looking for instead of having access to the entire OBB/data folder. ( I would like to play this game on Android 13 and I hope this is helpful to the development of the next version).

![Screenshot_20220831-181943](https://user-images.githubusercontent.com/55955972/187795318-ac197ff8-e2fd-497a-b17f-6b04758a3517.png)

**Comment by Minwol** [comment]
I would love to go in and fix this but unfortunately I don't have the time. Here is a work around so you can still play though!

Settings > Apps > Special app access > All files access > com.zane.smapiinstaller (Enable it)
Run the SMAPI installer, it should ask for permission to that folder permission in obb but just swipe to go back and it should be generating the file. Then install! 

If it doesn't work, grant all permissions to the installer in app info before running.

Let me know if this works for you please

**Comment by lividhen** [comment]
> This workaround does work, it also found all the plugins that were installed and lets me configure them. Thanks for letting me know.
> 
> Why does the installer need OBB and data access anyway is it just for the save files?

OBB contains data like music and graphics. Some games store everything in a .obb file, like sonic the hedgehog, where as stardew i think just stores sound. Data i think is similar but idk the specifics.

**Comment by nick123456789025** [comment]
Thx

**Comment by vikas2316** [comment]
Only these permissions are showing up for me.
It is still asking for permission in app.
![Screenshot_20230102-202642_Permission controller](https://user-images.githubusercontent.com/44715137/210248782-61cc26a5-ea5f-4560-86cc-fb8a29e99abf.png)

**Comment by Minwol** [comment]
> Only these permissions are showing up for me. It is still asking for permission in app. ![Screenshot_20230102-202642_Permission controller](https://user-images.githubusercontent.com/44715137/210248782-61cc26a5-ea5f-4560-86cc-fb8a29e99abf.png)

That is the app permissions screen. You need to find the Special app access under Settings > Apps

**Comment by amruzi** [comment]
maybe my screenshot can help you. I use Xiaomi Pad 5

![Step 1 - mark](https://user-images.githubusercontent.com/28243190/227854670-4a36334c-3d85-4a7e-bbc6-4b80bbd1fdb3.jpg)
---
![Step 2-mark](https://user-images.githubusercontent.com/28243190/227854677-cc9b92da-7f1f-4f89-85d8-bf92157849ad.jpg)
---
![Step 3 - mark](https://user-images.githubusercontent.com/28243190/227854678-fe3e747b-9326-4fb9-8afc-ce94270ead3f.jpg)
---
![Step 4 -](https://user-images.githubusercontent.com/28243190/227854683-429ed468-1dbd-4643-9efa-17abfdb19da3.jpg)

**Comment by Wonder871** [comment]
Hm?

**Comment by Andremamanks** [comment]
Bro, you forgot to switch language... Me myself can understand it but some
other are confused

Pada tanggal Sen, 27 Mar 2023 13:08, Amruzi Nugrahardiawan <
***@***.***> menulis:

**Comment by kenth246** [comment]
I kinda have the same problem. When I'm giving my the game access to its folder inside Android/data, i cannot give access to the path. I already did give SMAPI installer the All File Access.
![Screenshot_20230921-234635](https://github.com/ZaneYork/SMAPI-Android-Installer/assets/145703786/502f4556-3d2c-4c80-ad1b-fd6dfe6b7527)

**Comment by uditkandari** [comment]
I did all the steps even gave special apps permission but getting this error
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.zane.stardewvalley/crc648e5438a58262f792.SMainActivity}: java.lang.ClassNotFoundException: com.google.android.vending.licensing.AESObfuscator
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3909)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4055)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2415)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8400)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
Caused by: java.lang.ClassNotFoundException: com.google.android.vending.licensing.AESObfuscator
	at crc648e5438a58262f792.SMainActivity.n_onCreate(Native Method)
	at crc648e5438a58262f792.SMainActivity.onCreate(SMainActivity.java:31)
	at android.app.Activity.performCreate(Activity.java:8538)
	at android.app.Activity.performCreate(Activity.java:8502)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1440)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3890)
	... 12 more
