### ISSUE TITLE
mod crashed on entry

### ISSUE THREAD

**Issue by santmelly** [ZaneYork/SMAPI-Android-Installer#24]
Hello, it's seems like I can't load several mods (like spacecore/json/tmxl etc.) It's sadi "mod crashed on entry and might not work correctly.

Here's my log
https://smapi.io/log/5b51f6d82ffa4d6e92c0a3b70efe1b9c

**Comment by tenting** [comment]
I'm not the mod author; just wanted to say that the link leads to the dreaded "Oops, couldn't parse that log." error from the SMAPI log parser.   Could you upload your log again and post the link?

**Comment by jarrelldean44** [comment]
Can u help me too its not working keep saying broken mod code and it freezes and close the app. Im on mobile 
  https://smapi.io/log/aeaa309fef424cd1a1d54bd5eb28f322

**Comment by ZaneYork** [comment]
> Can u help me too its not working keep saying broken mod code and it freezes and close the app. Im on mobile
> https://smapi.io/log/aeaa309fef424cd1a1d54bd5eb28f322

Will fix in next release, you can try this [pre-release ](https://drive.google.com/file/d/1XQv4PBvrP-w7EwkgGzmkC645tehcSioe/view?usp=sharing)to test TMX Loader fix

**Comment by jarrelldean44** [comment]
Hi anyone know how to fix cjb item spawner. Like everything i press 'I' on the virtual keyboard it just crashes and I did everything and it won't work. One time i moved it to my settings in stardew but idk how to do it bc Everytime i press "I" in the Virtual keyboard it crashes my game immediately. I play on android. And all my mods and everything work fine. It days it load no red or anything. Idk how to fix the bug or whatever.



[10:07:11 INFO  SMAPI] SMAPI 3.7.2 with Stardew Valley 1.4.5 on Android Unix 3.18.71.0
[10:07:11 INFO  SMAPI] Mods go here: /storage/emulated/0/StardewValley/Mods
[10:07:11 TRACE SMAPI] (Using custom --mods-path argument.)
[10:07:11 TRACE SMAPI] Log started at 2020-09-17T14:07:11 UTC
[10:07:11 TRACE SMAPI] Loaded with custom settings: GitHubProjectName: MartyrPher/SMAPI-Android-Installer, ModsPath: 
[10:07:17 WARN  SMAPI] Writing to the terminal is disabled because the --no-terminal argument was received. This usually means launching the terminal failed.
[10:07:17 DEBUG SMAPI] Starting game...
[10:07:23 TRACE SMAPI] Loading mod metadata...
[10:07:24 TRACE SMAPI] Loading mods...
[10:07:24 TRACE SMAPI]    CJB Cheats Menu (from Mods/CJB Cheats Menu 1.25.2-4-1-25-2-1599945374/CJBCheatsMenu/CJBCheatsMenu.dll)...
[10:07:25 TRACE SMAPI]       Rewriting CJBCheatsMenu.dll for OS...
[10:07:26 TRACE SMAPI]       Rewrote CJBCheatsMenu.dll to fix SpriteBatch methods...
[10:07:26 TRACE SMAPI]       Rewrote CJBCheatsMenu.dll to fix Game1 methods...
[10:07:26 TRACE SMAPI]       Rewrote CJBCheatsMenu.dll to fix IClickableMenu methods...
[10:07:26 TRACE SMAPI]       Rewrote CJBCheatsMenu.dll to fix Game1.currentLocation (field => property)...
[10:07:26 TRACE SMAPI]       Rewrote CJBCheatsMenu.dll to fix IClickableMenu.drawTextureBox (added missing optional parameters)...
[10:07:26 TRACE SMAPI]    CJB Item Spawner (from Mods/CJB Item Spawner 1.12.2-93-1-12-2-1599945967/CJBItemSpawner/CJBItemSpawner.dll)...
[10:07:26 TRACE SMAPI]       Rewriting CJBItemSpawner.dll for OS...
[10:07:26 TRACE SMAPI]       Rewrote CJBItemSpawner.dll to fix StardewValley.Menus.TextBox.Selected property...
[10:07:26 TRACE SMAPI]       Rewrote CJBItemSpawner.dll to fix IClickableMenu methods...
[10:07:26 TRACE SMAPI]       Rewrote CJBItemSpawner.dll to fix Game1.currentLocation (field => property)...
[10:07:26 TRACE SMAPI]       Rewrote CJBItemSpawner.dll to fix IClickableMenu.drawTextureBox (added missing optional parameters)...
[10:07:26 TRACE SMAPI]       Rewrote CJBItemSpawner.dll to fix TextBox..ctor (added missing optional parameters)...
[10:07:26 TRACE SMAPI]       Rewrote CJBItemSpawner.dll to fix Utility.trashItem (added missing optional parameters)...
[10:07:26 TRACE SMAPI]       Rewrote CJBItemSpawner.dll to fix Utility.getTrashReclamationPrice (added missing optional parameters)...
[10:07:26 TRACE SMAPI]       Rewrote CJBItemSpawner.dll to fix Game1.parseText (added missing optional parameters)...
[10:07:26 TRACE SMAPI]    Console Commands (from Mods/Console Commands/ConsoleCommands.dll)...
[10:07:27 TRACE SMAPI]    Content Patcher (from Mods/Content Patcher 1.18.2-1915-1-18-2-1600049052/ContentPatcher/ContentPatcher.dll)...
[10:07:27 TRACE SMAPI]       Rewriting ContentPatcher.dll for OS...
[10:07:28 TRACE SMAPI]       Rewrote ContentPatcher.dll to fix SpriteBatch methods...
[10:07:28 TRACE SMAPI]       Rewrote ContentPatcher.dll to fix StardewValley.Game1.isRaining field...
[10:07:28 TRACE SMAPI]       Rewrote ContentPatcher.dll to fix StardewValley.Game1.isSnowing field...
[10:07:28 TRACE SMAPI]       Rewrote ContentPatcher.dll to fix StardewValley.Game1.isDebrisWeather field...
[10:07:28 TRACE SMAPI]       Rewrote ContentPatcher.dll to fix Game1.currentLocation (field => property)...
[10:07:28 TRACE SMAPI]       Rewrote ContentPatcher.dll to fix IClickableMenu.drawTextureBox (added missing optional parameters)...
[10:07:28 TRACE SMAPI]    Custom Localization (from Mods/CustomLocalization/CustomLocalization.dll)...
[10:07:28 TRACE SMAPI]       Rewriting CustomLocalization.dll for OS...
[10:07:29 TRACE SMAPI]       Rewrote CustomLocalization.dll to fix StardewValley.Game1.onScreenMenus field...
[10:07:29 TRACE SMAPI]       Detected game patcher (Harmony.HarmonyInstance type) in assembly CustomLocalization.dll.
[10:07:29 TRACE SMAPI]    Custom NPC Fixes (from Mods/CustomNPCFixes/CustomNPCFixes.dll)...
[10:07:29 TRACE SMAPI]       Rewriting CustomNPCFixes.dll for OS...
[10:07:29 TRACE SMAPI]       Rewrote CustomNPCFixes.dll to fix NPC methods...
[10:07:29 TRACE SMAPI]    Farm Type Manager (from Mods/FarmTypeManager/FarmTypeManager.dll)...
[10:07:29 TRACE SMAPI]       Rewriting FarmTypeManager.dll for OS...
[10:07:29 TRACE SMAPI]       Rewrote FarmTypeManager.dll to fix StardewValley.Game1.isRaining field...
[10:07:29 TRACE SMAPI]       Rewrote FarmTypeManager.dll to fix StardewValley.Game1.isSnowing field...
[10:07:29 TRACE SMAPI]       Rewrote FarmTypeManager.dll to fix StardewValley.Game1.isDebrisWeather field...
[10:07:29 TRACE SMAPI]       Rewrote FarmTypeManager.dll to fix StardewValley.GameLocation.debris field...
[10:07:29 TRACE SMAPI]       Rewrote FarmTypeManager.dll to fix Game1.currentLocation (field => property)...
[10:07:29 TRACE SMAPI]       Rewrote FarmTypeManager.dll to fix Farmer.couldInventoryAcceptThisItem (added missing optional parameters)...
[10:07:29 TRACE SMAPI]       Detected game patcher (Harmony.HarmonyInstance type) in assembly FarmTypeManager.dll.
[10:07:30 TRACE SMAPI]    Save Backup (from Mods/SaveBackup/SaveBackup.dll)...
[10:07:30 TRACE SMAPI]       Rewriting SaveBackup.dll for OS...
[10:07:30 TRACE SMAPI]    Tractor Mod (from Mods/TractorMod/TractorMod.dll)...
[10:07:30 TRACE SMAPI]       Rewriting TractorMod.dll for OS...
[10:07:30 TRACE SMAPI]       Rewrote TractorMod.dll to fix SpriteBatch methods...
[10:07:30 TRACE SMAPI]       Rewrote TractorMod.dll to fix Game1.currentLocation (field => property)...
[10:07:30 TRACE SMAPI]       Rewrote TractorMod.dll to fix IClickableMenu.drawTextureBox (added missing optional parameters)...
[10:07:31 TRACE SMAPI]    VirtualKeyboard (from Mods/VirtualKeyboard/VirtualKeyboard.dll)...
[10:07:31 INFO  SMAPI] Loaded 10 mods:
[10:07:31 INFO  SMAPI]    CJB Cheats Menu 1.25.2 by CJBok and Pathoschild | Simple in-game cheats menu!
[10:07:31 INFO  SMAPI]    CJB Item Spawner 1.12.2 by CJBok and Pathoschild | Simple in-game item spawner!
[10:07:31 INFO  SMAPI]    Console Commands 3.1.0 by SMAPI | Adds SMAPI console commands that let you manipulate the game.
[10:07:31 INFO  SMAPI]    Content Patcher 1.18.2 by Pathoschild | Loads content packs which edit game data, images, and maps without changing the game files.
[10:07:31 INFO  SMAPI]    Custom Localization 1.1.0 by ZaneYork | Localization for not exist locale.
[10:07:31 INFO  SMAPI]    Custom NPC Fixes 1.2.1 by spacechase0 | Fixes for Custom NPCs.
[10:07:31 INFO  SMAPI]    Farm Type Manager 1.11.0 by Esca | Allows custom spawning of content from each farm type: forage, large objects, ore, and monsters
[10:07:31 INFO  SMAPI]    Save Backup 3.1.0 by SMAPI | Automatically backs up all your saves once per day into its folder.
[10:07:31 INFO  SMAPI]    Tractor Mod 4.11.2 by Pathoschild | Lets you buy a tractor to more efficiently work with crops, clear twigs and rocks, etc.
[10:07:31 INFO  SMAPI]    VirtualKeyboard 3.3.0 by SMAPI | A much needed Virtual Keyboard for SMAPI Android.

[10:07:31 INFO  SMAPI] Found 2 mods with warnings:
[10:07:31 INFO  SMAPI]    Patched game code
[10:07:31 INFO  SMAPI]    --------------------------------------------------
[10:07:31 INFO  SMAPI]       These mods directly change the game code. They're more likely to cause errors or bugs in-game; if
[10:07:31 INFO  SMAPI]       your game has issues, try removing these first. Otherwise you can ignore this warning.

[10:07:31 INFO  SMAPI]       - Custom Localization
[10:07:31 INFO  SMAPI]       - Farm Type Manager

[10:07:31 TRACE CJB Cheats Menu] Started with menu key I.
[10:07:31 TRACE CJB Item Spawner] Started with menu key P.
[10:07:31 TRACE SMAPI]    Found mod-provided API (ContentPatcher.Framework.ContentPatcherAPI).
[10:07:37 TRACE Farm Type Manager] Applying Harmony patch "HarmonyPatch_AddSpawnedMineralsToCollections": prefixing SDV method "Farmer.addItemToInventoryBool(Item, bool)".
[10:07:37 TRACE Farm Type Manager] Applying Harmony patch "HarmonyPatch_UpdateCursorOverPlacedItem": postfixing SDV method "Utility.canGrabSomethingFromHere(int, int, Farmer)".
[10:07:38 TRACE SMAPI] Checking for updates...
[10:07:38 TRACE SMAPI]    Checking for updates to 8 mods...
[10:07:38 TRACE SMAPI] Detecting common issues...
[10:07:39 TRACE SMAPI] Got update-check errors for some mods:
   Custom NPC Fixes: System.NullReferenceException: Object reference not set to an instance of an object.
   at StardewModdingAPI.Web.Framework.Clients.Chucklefish.ChucklefishClient.GetModData(String id) in C:\source\_Stardew\SMAPI\src\SMAPI.Web\Framework\Clients\Chucklefish\ChucklefishClient.cs:line 77
   at StardewModdingAPI.Web.Framework.ModSiteManager.GetModPageAsync(UpdateKey updateKey) in C:\source\_Stardew\SMAPI\src\SMAPI.Web\Framework\ModSiteManager.cs:line 53
   VirtualKeyboard: The value 'null' isn't a valid Nexus mod ID, must be an integer ID.
[10:07:39 TRACE SMAPI]    All mods up to date.
[10:07:39 TRACE SMAPI] Invalidating cached assets for new editors & loaders...
[10:07:39 TRACE SMAPI]    changed: Content Patcher (added 1)
[10:07:39 TRACE SMAPI] Invalidated 0 cache entries.
[10:07:54 DEBUG SMAPI] SaveParsed
[10:08:00 DEBUG SMAPI] SaveLoadedBasicInfo
[10:08:07 DEBUG SMAPI] SaveLoadedLocations
[10:08:08 DEBUG SMAPI] Preloaded
[10:08:08 TRACE SMAPI] Game loader done.
[10:08:09 TRACE SMAPI] Context: loaded save 'Namer_259647007', starting spring 3 Y1, locale set to en. Single-player.
[10:08:11 TRACE Farm Type Manager] Day is starting. Loading config data.
[10:08:11 TRACE Farm Type Manager] Beginning file loading process...
[10:08:11 TRACE Farm Type Manager] All available content packs checked.
[10:08:11 TRACE Farm Type Manager] Loading files from FarmTypeManager/data
[10:08:11 TRACE Farm Type Manager] Validating data from FarmTypeManager/data
[10:08:11 TRACE Farm Type Manager] Checking for duplicate UniqueAreaIDs...
[10:08:11 TRACE Farm Type Manager] Assigning new UniqueAreaIDs to any blanks or duplicates...
[10:08:11 TRACE Farm Type Manager] Validation complete for data from FarmTypeManager/data
[10:08:11 TRACE Farm Type Manager] Checking file conditions...
[10:08:11 TRACE Farm Type Manager] FarmTypeManager/data farm data loaded successfully.
[10:08:11 TRACE Farm Type Manager] Checking for saved objects that went missing overnight.
[10:08:11 TRACE Farm Type Manager] Starting forage generation for this file: FarmTypeManager/data/Namer_259647007.json
[10:08:11 TRACE Farm Type Manager] Forage generation is disabled for this file.
[10:08:11 TRACE Farm Type Manager] All files and content packs checked. Forage generation process complete.
[10:08:11 TRACE Farm Type Manager] Starting large object generation for this file: FarmTypeManager/data/Namer_259647007.json
[10:08:11 TRACE Farm Type Manager] Large object generation is disabled for this file.
[10:08:11 TRACE Farm Type Manager] All files and content packs checked. Large object generation process complete.
[10:08:11 TRACE Farm Type Manager] Starting ore generation for this file: FarmTypeManager/data/Namer_259647007.json
[10:08:11 TRACE Farm Type Manager] Ore generation is disabled for this file.
[10:08:11 TRACE Farm Type Manager] All files and content packs checked. Ore spawn process complete.
[10:08:11 TRACE Farm Type Manager] Starting monster generation for this file: FarmTypeManager/data/Namer_259647007.json
[10:08:11 TRACE Farm Type Manager] Monster generation is disabled for this file.
[10:08:11 TRACE Farm Type Manager] All files and content packs checked. Monster generation process complete.
[10:08:20 TRACE Farm Type Manager] Spawning objects set to appear at time: 920...
[10:08:20 TRACE Farm Type Manager] Spawn process complete. Time: 920. Total objects spawned: 0.
[10:08:26 ERROR SMAPI] Critical app domain exception: System.NullReferenceException: Object reference not set to an instance of an object
  at CJBItemSpawner.Framework.ItemMenuWithInventory.performHoverAction (System.Int32 x, System.Int32 y) [0x00000] in <9965b84bebca4170a7a8773ee775d1ff>:0 
  at StardewValley.Menus.ClickableComponent.containsPoint (System.Int32 x, System.Int32 y) [0x0000a] in <92abaa5e9143444aa721588ec858d3ea>:0 
  at System.Buffer.Memcpy (System.Byte* dest, System.Byte* src, System.Int32 len) [0x00073] in <d4a23bbd2f544c30a48c44dd622ce09f>:0

**Comment by ZaneYork** [comment]
The errorlog is not available, please upload it properly and reopen this issue again if it still exists
