### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by enesh0** [ZaneYork/SMAPI-Android-Installer#264]
java.lang.RuntimeException: Unable to get provider androidx.core.content.FileProvider: java.lang.ClassNotFoundException: Didn't find class "androidx.core.content.FileProvider" on path: DexPathList[[zip file "/data/app/~~EN9nK7pBGV6Q_HTESmyNEQ==/com.zane.stardewvalley-JKEqiUqGtkNt9bcK2oqWGQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~EN9nK7pBGV6Q_HTESmyNEQ==/com.zane.stardewvalley-JKEqiUqGtkNt9bcK2oqWGQ==/lib/arm64, /data/app/~~EN9nK7pBGV6Q_HTESmyNEQ==/com.zane.stardewvalley-JKEqiUqGtkNt9bcK2oqWGQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system/system_ext/lib64]]
	at android.app.ActivityThread.installProvider(ActivityThread.java:7843)
	at android.app.ActivityThread.installContentProviders(ActivityThread.java:7349)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7079)
	at android.app.ActivityThread.access$1700(ActivityThread.java:273)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2166)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8279)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:576)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1074)
Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.core.content.FileProvider" on path: DexPathList[[zip file "/data/app/~~EN9nK7pBGV6Q_HTESmyNEQ==/com.zane.stardewvalley-JKEqiUqGtkNt9bcK2oqWGQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~EN9nK7pBGV6Q_HTESmyNEQ==/com.zane.stardewvalley-JKEqiUqGtkNt9bcK2oqWGQ==/lib/arm64, /data/app/~~EN9nK7pBGV6Q_HTESmyNEQ==/com.zane.stardewvalley-JKEqiUqGtkNt9bcK2oqWGQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system/system_ext/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at android.app.AppComponentFactory.instantiateProvider(AppComponentFactory.java:147)
	at android.app.ActivityThread.installProvider(ActivityThread.java:7827)
	... 11 more

**Comment by EmilyLioness** [comment]
My keeps closing please help me bring the Mod Meau back

**Comment by lividhen** [comment]
If you are on 1.5 you can build the unfinished version from this repo.
