### ISSUE TITLE
smapi crashes and won't open after downloading

### ISSUE THREAD

**Issue by stanbits8** [ZaneYork/SMAPI-Android-Installer#376]
error on xiaomi 12 pro

java.lang.RuntimeException: Unable to get provider androidx.core.content.FileProvider: java.lang.ClassNotFoundException: Didn't find class "androidx.core.content.FileProvider" on path: DexPathList[[zip file "/data/app/~~D8ALmbiE4nL1YaGGIQ8X_Q==/com.zane.stardewvalley-xZfCqO6cmRUlEDXgujsCQA==/base.apk"],nativeLibraryDirectories=[/data/app/~~D8ALmbiE4nL1YaGGIQ8X_Q==/com.zane.stardewvalley-xZfCqO6cmRUlEDXgujsCQA==/lib/arm64, /data/app/~~D8ALmbiE4nL1YaGGIQ8X_Q==/com.zane.stardewvalley-xZfCqO6cmRUlEDXgujsCQA==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
	at android.app.ActivityThread.installProvider(ActivityThread.java:7699)
	at android.app.ActivityThread.installContentProviders(ActivityThread.java:7205)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6947)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2189)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8116)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.core.content.FileProvider" on path: DexPathList[[zip file "/data/app/~~D8ALmbiE4nL1YaGGIQ8X_Q==/com.zane.stardewvalley-xZfCqO6cmRUlEDXgujsCQA==/base.apk"],nativeLibraryDirectories=[/data/app/~~D8ALmbiE4nL1YaGGIQ8X_Q==/com.zane.stardewvalley-xZfCqO6cmRUlEDXgujsCQA==/lib/arm64, /data/app/~~D8ALmbiE4nL1YaGGIQ8X_Q==/com.zane.stardewvalley-xZfCqO6cmRUlEDXgujsCQA==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at android.app.AppComponentFactory.instantiateProvider(AppComponentFactory.java:147)
	at android.app.ActivityThread.installProvider(ActivityThread.java:7683)
	... 11 more

don't know what to do anymore 😭

**Comment by stanbits8** [comment]
deleted and installed from scratch, worked fine
