### ISSUE TITLE
SMAPI keeps crashing and give this error

### ISSUE THREAD

**Issue by NoLaw-FR** [ZaneYork/SMAPI-Android-Installer#529]
So, I uninstalled and deleted all folders and reinstalled all of this, I did everything right, with latest versions, but when I open the patched game, he keep crashing and here what my phone give me 

![Screenshot_2023-08-02-10-37-47-013_com miui bugreport](https://github.com/ZaneYork/SMAPI-Android-Installer/assets/116680874/f5bc85d0-7c03-4bac-ae81-ae65ce89b113)

**Comment by Jangko123** [comment]
Keep trying until you find the solution 

https://smapi.io/log/01f626a9669b4b298b63a0b3742d5e0e

**Comment by NoLaw-FR** [comment]
I'ma just wait, I already tested everything that came to my mind so yeah, I'll wait ig

**Comment by Dani141990** [comment]
I seemed to have similar problem but with the music instead. 

Java.IO.FileNotFoundException: Content/XACT/music.xwb
  at Java.Interop.JniEnvironment+InstanceMethods.CallObjectMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x0006e] in <ee6843d645da44b0965c1ea204d315bd>:0 
  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeAbstractObjectMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x00024] in <ee6843d645da44b0965c1ea204d315bd>:0 
  at Android.Content.Res.AssetManager.Open (System.String fileName) [0x00029] in <8638e88f61db46e4bc35e66b77e3b3e8>:0 
  at Microsoft.Xna.Framework.TitleContainer.PlatformOpenStream (System.String safeName) [0x0001c] in <4ed3ea286e884e05923b85c565a4d988>:0 
  at Microsoft.Xna.Framework.TitleContainer.OpenStream (System.String name) [0x0001a] in <4ed3ea286e884e05923b85c565a4d988>:0 
  --- End of managed Java.IO.FileNotFoundException stack trace ---
java.io.FileNotFoundException: Content/XACT/music.xwb
	at android.content.res.AssetManager.nativeOpenAsset(Native Method)
	at android.content.res.AssetManager.open(AssetManager.java:881)
	at android.content.res.AssetManager.open(AssetManager.java:858)

**Comment by Kitty035** [comment]
I would get these errors but on older version of Smapi.  I fixed it simply by installing Smapi again.  Should not effect any mods, at least playing v3.7.6.9.  (Never got 3.7.6.10 to work so stuck with older version.)
