### ISSUE TITLE
Not work for version 1.5.6.51

### ISSUE THREAD

**Issue by lululoid** [ZaneYork/SMAPI-Android-Installer#564]
The force closed as soon as I opened the patched game. I don't know if this log will help but this is it.

<pre>--------- beginning of main
09-12 12:13:00.040 10230 10230 I e.stardewvalle: Using CollectorTypeCC GC.
09-12 12:13:00.048 10230 10230 E e.stardewvalle: Not starting debugger since process cannot load the jdwp agent.
09-12 12:13:00.051 10230 10230 D ProcessState: Binder ioctl to enable oneway spam detection failed: Invalid argument
09-12 12:13:00.105 10230 10230 I MessageMonitor: Load libmiui_runtime
09-12 12:13:00.303 10230 10230 D CompatibilityChangeReporter: Compat change id reported: 171979766; UID 10447; state: ENABLED
09-12 12:13:00.318 10230 10284 D AppScoutStateMachine: 10230-ScoutStateMachinecreated
09-12 12:13:00.330 10230 10230 D ApplicationLoaders: Returning zygote-cached class loader: /system/framework/android.test.base.jar
09-12 12:13:00.337 10230 10230 D nativeloader: Configuring classloader-namespace for other apk /data/app/~~fPlkuXVfIAWPq4nTqbMUDQ==/com.zane.stardewvalley-1mWATtshar8cfKtXCTRrAA==/base.apk. target_sdk_version=33, uses_libraries=, library_path=/data/app/~~fPlkuXVfIAWPq4nTqbMUDQ==/com.zane.stardewvalley-1mWATtshar8cfKtXCTRrAA==/lib/arm64:/data/app/~~fPlkuXVfIAWPq4nTqbMUDQ==/com.zane.stardewvalley-1mWATtshar8cfKtXCTRrAA==/base.apk!/lib/arm64-v8a, permitted_path=/data:/mnt/expand:/data/user/0/com.zane.stardewvalley
09-12 12:13:00.358 10230 10230 I Perf    : Connecting to perf service.
09-12 12:13:00.369 10230 10230 V GraphicsEnvironment: ANGLE Developer option for 'com.zane.stardewvalley' set to: 'default'
09-12 12:13:00.369 10230 10230 V GraphicsEnvironment: Neither updatable production driver nor prerelease driver is supported.
--------- beginning of system
09-12 12:13:00.380 10230 10230 I ForceDarkHelperStubImpl: initialize for com.zane.stardewvalley , ForceDarkOrigin
09-12 12:13:00.383 10230 10230 D OpenGLRenderer: JNI_OnLoad success
09-12 12:13:00.383 10230 10230 I MiuiForceDarkConfig: setConfig density:2.000000, mainRule:0, secondaryRule:0, tertiaryRule:0
09-12 12:13:00.389 10230 10230 D NetworkSecurityConfig: No Network Security Config specified, using platform default
09-12 12:13:00.390 10230 10230 D NetworkSecurityConfig: No Network Security Config specified, using platform default
09-12 12:13:00.432 10230 10230 W monodroid: Creating public update directory: `/data/user/0/com.zane.stardewvalley/files/.__override__`
09-12 12:13:00.438 10230 10230 W monodroid: runtime args empty
09-12 12:13:00.479 10230 10230 W monodroid-gc: GREF GC Threshold: 46080
09-12 12:13:01.985 10230 10230 V mono-stdout: static SaveGame() - begin
09-12 12:13:02.042 10230 10230 V mono-stdout: static SaveGame() - end
09-12 12:13:02.043 10230 10230 V mono-stdout: Warning: serializer for type 'System.String' not found in pregenerated asm.
09-12 12:13:02.123 10230 10230 V mono-stdout: Warning: serializer for type 'System.Int64' not found in pregenerated asm.
09-12 12:13:02.131 10230 10230 V mono-stdout: MobileDisplay.SetDisplaySettings  1650x720 320 PPI
09-12 12:13:02.131 10230 10230 V mono-stdout: 		ZoomScale: 1.125
09-12 12:13:02.131 10230 10230 V mono-stdout: 		MenuButtonScale: 1.125
09-12 12:13:02.131 10230 10230 V mono-stdout: 		xEdge: 0
09-12 12:13:02.131 10230 10230 V mono-stdout: 		toolbarPaddingX: 0
09-12 12:13:02.131 10230 10230 V mono-stdout: 
09-12 12:13:02.144 10230 10230 D ViewScrollStubImpl: the value of mScrollFrictionRes is: 0.015
09-12 12:13:02.148 10230 10230 D MiuiMultiWindowUtils: freeform resolution args raw data:{  "zizhan":{    "freeform_args": {      "inner":{        "vertical_portrait":{"aspect_ratio":0.626, "original_ratio":0.5643,"original_scale":0.74,"top_margin":0.168,"left_margin":0.484},        "horizontal_portrait":{"aspect_ratio":0.626, "original_ratio":0.5643,"original_scale":0.74,"top_margin":0.1222,"left_margin":0.59745},        "vertical_landscape":{"aspect_ratio":1.6, "original_ratio":1,"original_scale":0.604,"top_margin":0.2596,"left_margin":0.2624},        "horizontal_landscape":{"aspect_ratio":1.6, "original_ratio":1,"original_scale":0.604,"top_margin":0.213,"left_margin":0.3758}      },      "outer":{        "vertical_portrait":{"aspect_ratio":0.626, "original_ratio":1,"original_scale":0.74,"top_margin":0.0753,"left_margin":-1},        "horizontal_portrait":{"aspect_ratio":0.626, "original_ratio":1,"original_scale":0.5756,"top_margin":-1,"left_margin":0.0753},        "vertical_landscape":{"aspect_ratio":1.6, "original_ratio":0.6847,"original_scale":0.587,"top_margin":0.0753,"left_margin":-1},        "horizontal_landscape":{"aspect_ratio":1.6, "original_ratio":0.6847,"original_scale":0.587,"top_margin":-1,"left_margin":0.0753}}    },    "mini_freeform_args":{      "inner":{        "vertical_portrait":{"aspect_ratio":0.626, "original_ratio":0.147},        "horizontal_portrait":{"aspect_ratio":0.626, "original_ratio":0.147},        "vertical_landscape":{"aspect_ratio":1.6, "original_ratio":0.165},        "horizontal_landscape":{"aspect_ratio":1.6, "original_ratio":0.165}      },      "outer":{        "vertical_portrait":{"aspect_ratio":0.626, "original_ratio":0.26},        "horizontal_portrait":{"aspect_ratio":0.626, "original_ratio":0.26},        "vertical_landscape":{"aspect_ratio":1.6, "original_ratio":0.293},        "horizontal_landscape":{"aspect_ratio":1.6, "original_ratio":0.293}}    }  },  "wide_default":{    "freeform_args": {        "vertical_portrait":{"aspect_ratio":0.625, "original_ratio":0.58,"original_scale":0.7574,"top_margin":0.125,"left_margin":-1},        "horizontal_portrait":{"aspect_ratio":0.625, "original_ratio":0.58,"original_scale":0.7574,"top_margin":-1,"left_margin":0.0714},        "vertical_landscape":{"aspect_ratio":1.6, "original_ratio":1,"original_scale":0.5153,"top_margin":0.125,"left_margin":-1},        "horizontal_landscape":{"aspect_ratio":1.6, "original_ratio":1,"original_scale":0.5153,"top_margin":-1,"left_margin":0.0714}    },    "mini_freeform_args":{        "vertical_portrait":{"aspect_ratio":0.5625, "original_ratio":0.144},        "horizontal_portrait":{"aspect_ratio":0.5625, "original_ratio":0.144},        "vertical_landscape":{"aspect_ratio":-1, "original_ratio":0.144},        "horizontal_landscape":{"aspect_ratio":-1, "original_ratio":0.144}    }  },  "narrow_default": {    "freeform_args": {        "vertical_portrait":{"aspect_ratio":0.5625, "original_ratio":1,"original_scale":0.7182,"top_margin":0.142,"left_margin":-1},        "horizontal_portrait":{"aspect_ratio":0.8, "original_ratio":1,"original_scale":0.7182,"top_margin":-1,"left_margin":0.05},        "vertical_landscape":{"aspect_ratio":1.6, "original_ratio":0.6545,"original_scale":0.4473,"top_margin":0.142,"left_margin":-1},        "horizontal_landscape":{"aspect_ratio":1.6, "original_ratio":0.6545,"original_scale":0.4473,"top_margin":-1,"left_margin":0.05}    },    "mini_freeform_args":{        "vertical_portrait":{"aspect_ratio":0.5625, "original_ratio":0.3},        "horizontal_portrait":{"aspect_ratio":0.5625, "original_ratio":0.3},        "vertical_landscape":{"aspect_ratio":1.7778, "original_ratio":0.3},        "horizontal_landscape":{"aspect_ratio":1.7778, "original_ratio":0.3}    }  },  "regular_default": {    "freeform_args": {      "vertical_portrait":{"aspect_ratio":0.625, "original_ratio":1,"original_scale":0.7,"top_margin":0.109,"left_margin":-1},      "horizontal_portrait":{"aspect_ratio":0.6667, "original_ratio":1,"original_scale":0.6102,"top_margin":-1,"left_margin":0.026},      "vertical_landscape":{"aspect_ratio
09-12 12:13:02.148 10230 10230 W System.err: org.json.JSONException: No value for fog
09-12 12:13:02.149 10230 10230 W System.err: 	at org.json.JSONObject.get(JSONObject.java:398)
09-12 12:13:02.149 10230 10230 W System.err: 	at org.json.JSONObject.getJSONObject(JSONObject.java:618)
09-12 12:13:02.149 10230 10230 W System.err: 	at android.util.MiuiMultiWindowUtils.initFreeFormResolutionArgsOfDevice(MiuiMultiWindowUtils.java:1433)
09-12 12:13:02.149 10230 10230 W System.err: 	at android.util.MiuiMultiWindowUtils.initFreeFormResolutionArgs(MiuiMultiWindowUtils.java:1427)
09-12 12:13:02.149 10230 10230 W System.err: 	at android.util.MiuiMultiWindowUtils.<clinit>(MiuiMultiWindowUtils.java:209)
09-12 12:13:02.149 10230 10230 W System.err: 	at android.util.MiuiMultiWindowUtils.isSupportMultiSwitchFeature(MiuiMultiWindowUtils.java:3351)
09-12 12:13:02.149 10230 10230 W System.err: 	at com.android.internal.policy.DecorViewMultiWinStubImpl.<init>(DecorViewMultiWinStubImpl.java:19)
09-12 12:13:02.149 10230 10230 W System.err: 	at com.android.internal.policy.DecorViewMultiWinStubImpl$Provider.provideNewInstance(DecorViewMultiWinStubImpl$Provider.java:14)
09-12 12:13:02.149 10230 10230 W System.err: 	at com.android.internal.policy.DecorViewMultiWinStubImpl$Provider.provideNewInstance(DecorViewMultiWinStubImpl$Provider.java:8)
09-12 12:13:02.149 10230 10230 W System.err: 	at com.miui.base.MiuiStubRegistry.get(MiuiStubRegistry.java:129)
09-12 12:13:02.149 10230 10230 W System.err: 	at com.miui.base.MiuiStubUtil.newInstance(MiuiStubUtil.java:77)
09-12 12:13:02.149 10230 10230 W System.err: 	at com.android.internal.policy.DecorViewMultiWinStub.newInstance(DecorViewMultiWinStub.java:11)
09-12 12:13:02.149 10230 10230 W System.err: 	at com.android.internal.policy.DecorView.<init>(DecorView.java:333)
09-12 12:13:02.149 10230 10230 W System.err: 	at com.android.internal.policy.PhoneWindow.generateDecor(PhoneWindow.java:2380)
09-12 12:13:02.149 10230 10230 W System.err: 	at com.android.internal.policy.PhoneWindow.installDecor(PhoneWindow.java:2760)
09-12 12:13:02.149 10230 10230 W System.err: 	at com.android.internal.policy.PhoneWindow.getDecorView(PhoneWindow.java:2140)
09-12 12:13:02.149 10230 10230 W System.err: 	at crc648e5438a58262f792.SMainActivity.n_onCreate(Native Method)
09-12 12:13:02.149 10230 10230 W System.err: 	at crc648e5438a58262f792.SMainActivity.onCreate(SMainActivity.java:31)
09-12 12:13:02.149 10230 10230 W System.err: 	at android.app.Activity.performCreate(Activity.java:8176)
09-12 12:13:02.149 10230 10230 W System.err: 	at android.app.Activity.performCreate(Activity.java:8143)
09-12 12:13:02.149 10230 10230 W System.err: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1330)
09-12 12:13:02.149 10230 10230 W System.err: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3744)
09-12 12:13:02.149 10230 10230 W System.err: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3938)
09-12 12:13:02.149 10230 10230 W System.err: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
09-12 12:13:02.149 10230 10230 W System.err: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
09-12 12:13:02.149 10230 10230 W System.err: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
09-12 12:13:02.149 10230 10230 W System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2291)
09-12 12:13:02.149 10230 10230 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:106)
09-12 12:13:02.149 10230 10230 W System.err: 	at android.os.Looper.loopOnce(Looper.java:210)
09-12 12:13:02.149 10230 10230 W System.err: 	at android.os.Looper.loop(Looper.java:299)
09-12 12:13:02.149 10230 10230 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:8309)
09-12 12:13:02.149 10230 10230 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
09-12 12:13:02.149 10230 10230 W System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
09-12 12:13:02.149 10230 10230 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1038)
09-12 12:13:02.149 10230 10230 D IS_CTS_MODE: false
09-12 12:13:02.149 10230 10230 D MULTI_WINDOW_SWITCH_ENABLED: false
09-12 12:13:02.150 10230 10230 D IS_CTS_MODE: false
09-12 12:13:02.150 10230 10230 D MULTI_WINDOW_SWITCH_ENABLED: false
09-12 12:13:02.153 10230 10230 D DecorView[]: getWindowModeFromSystem  windowmode is 1
09-12 12:13:02.268 10230 10230 D AndroidRuntime: Shutting down VM
--------- beginning of crash
09-12 12:13:02.268 10230 10230 E AndroidRuntime: FATAL EXCEPTION: main
09-12 12:13:02.268 10230 10230 E AndroidRuntime: Process: com.zane.stardewvalley, PID: 10230
09-12 12:13:02.268 10230 10230 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.zane.stardewvalley/crc648e5438a58262f792.SMainActivity}: java.lang.ClassNotFoundException: com.google.android.vending.licensing.AESObfuscator
09-12 12:13:02.268 10230 10230 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3771)
09-12 12:13:02.268 10230 10230 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3938)
09-12 12:13:02.268 10230 10230 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
09-12 12:13:02.268 10230 10230 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
09-12 12:13:02.268 10230 10230 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
09-12 12:13:02.268 10230 10230 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2291)
09-12 12:13:02.268 10230 10230 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
09-12 12:13:02.268 10230 10230 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:210)
09-12 12:13:02.268 10230 10230 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:299)
09-12 12:13:02.268 10230 10230 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8309)
09-12 12:13:02.268 10230 10230 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-12 12:13:02.268 10230 10230 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
09-12 12:13:02.268 10230 10230 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1038)
09-12 12:13:02.268 10230 10230 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: com.google.android.vending.licensing.AESObfuscator
09-12 12:13:02.268 10230 10230 E AndroidRuntime: 	at crc648e5438a58262f792.SMainActivity.n_onCreate(Native Method)
09-12 12:13:02.268 10230 10230 E AndroidRuntime: 	at crc648e5438a58262f792.SMainActivity.onCreate(SMainActivity.java:31)
09-12 12:13:02.268 10230 10230 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8176)
09-12 12:13:02.268 10230 10230 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8143)
09-12 12:13:02.268 10230 10230 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1330)
09-12 12:13:02.268 10230 10230 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3744)
09-12 12:13:02.268 10230 10230 E AndroidRuntime: 	... 12 more
09-12 12:13:02.270 10230 10230 W OOMEventManagerFK: Failed to mkdir /data/mqsas/hprof/
09-12 12:13:02.293 10230 10230 I MonoDroid: UNHANDLED EXCEPTION:
09-12 12:13:02.307 10230 10230 I MonoDroid: Java.Lang.RuntimeException: Unable to start activity ComponentInfo{com.zane.stardewvalley/crc648e5438a58262f792.SMainActivity}: java.lang.ClassNotFoundException: com.google.android.vending.licensing.AESObfuscator ---> Java.Lang.ClassNotFoundException: com.google.android.vending.licensing.AESObfuscator
09-12 12:13:02.307 10230 10230 I MonoDroid:   at Java.Interop.JniEnvironment+Types.TryFindClass (System.String classname, System.Boolean throwOnError) [0x0017a] in <ee6843d645da44b0965c1ea204d315bd>:0 
09-12 12:13:02.307 10230 10230 I MonoDroid:   at Java.Interop.JniEnvironment+Types.FindClass (System.String classname) [0x00000] in <ee6843d645da44b0965c1ea204d315bd>:0 
09-12 12:13:02.307 10230 10230 I MonoDroid:   at Java.Interop.JniType..ctor (System.String classname) [0x00006] in <ee6843d645da44b0965c1ea204d315bd>:0 
09-12 12:13:02.307 10230 10230 I MonoDroid:   at Java.Interop.JniType.GetCachedJniType (Java.Interop.JniType& cachedType, System.String classname) [0x00018] in <ee6843d645da44b0965c1ea204d315bd>:0 
09-12 12:13:02.307 10230 10230 I MonoDroid:   at Java.Interop.JniPeerMembers.get_JniPeerType () [0x0000c] in <ee6843d645da44b0965c1ea204d315bd>:0 
09-12 12:13:02.307 10230 10230 I MonoDroid:   at Java.Interop.JniPeerMembers+JniInstanceMethods.get_JniPeerType () [0x00014] in <ee6843d645da44b0965c1ea204d315bd>:0 
09-12 12:13:02.307 10230 10230 I MonoDroid:   at Java.Interop.JniPeerMembers+JniInstanceMethods.StartCreateInstance (System.String constructorSignature, System.Type declaringType, Java.Interop.JniArgumentValue* parameters) [0x0003f] in <ee6843d645da44b0965c1ea204d315bd>:0 
09-12 12:13:02.307 10230 10230 I MonoDroid:   at Google.Android.Vending.Licensing.AESObfuscator..ctor (System.Byte[] salt, System.String applicationId, System.String deviceId) [0x0008a] in <a1ee3f43e2004f78ad82ff32fc043502>:0 
09-12 12:13:02.307 10230 10230 I MonoDroid:   at StardewValley.MainActivity.DoLicenseCheck () [0x00075] in <92f51fbc629345f0928af1c1eafdc775>:0 
09-12 12:13:02.307 10230 10230 I MonoDroid:   at StardewValley.MainActivity.OnCreatePartTwo () [0x00053] in <92f51fbc629345f0928af1c1eafdc775>:0 
09-12 12:13:02.307 10230 10230 I MonoDroid:   at StardewValley.MainActivity.CheckAppPermissions () [0x00018] in <92f51fbc629345f0928af1c1eafdc775>:0 
09-12 12:13:02.307 10230 10230 I MonoDroid:   at StardewValley.MainActivity.OnCreate (Android.OS.Bundle bundle) [0x00063] in <92f51fbc629345f0928af1c1eafdc775>:0 
09-12 12:13:02.307 10230 10230 I MonoDroid:   at StardewModdingAPI.SMainActivity.OnCreate (Android.OS.Bundle bundle) [0x00170] in <a657c589ffdc433da6b7a1a6216be427>:0 
09-12 12:13:02.307 10230 10230 I MonoDroid:   at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState) [0x0000f] in <8638e88f61db46e4bc35e66b77e3b3e8>:0 
09-12 12:13:02.307 10230 10230 I MonoDroid:   at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPL_V (_JniMarshal_PPL_V callback, System.IntPtr jnienv, System.IntPtr klazz, System.IntPtr p0) [0x00005] in <8638e88f61db46e4bc35e66b77e3b3e8>:0 
09-12 12:13:02.307 10230 10230 I MonoDroid:    --- End of inner exception stack trace ---
09-12 12:13:02.307 10230 10230 I MonoDroid:   --- End of managed Java.Lang.RuntimeException stack trace ---
09-12 12:13:02.307 10230 10230 I MonoDroid: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.zane.stardewvalley/crc648e5438a58262f792.SMainActivity}: java.lang.ClassNotFoundException: com.google.android.vending.licensing.AESObfuscator
09-12 12:13:02.308 10230 10230 I MonoDroid: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3771)
09-12 12:13:02.308 10230 10230 I MonoDroid: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3938)
09-12 12:13:02.308 10230 10230 I MonoDroid: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
09-12 12:13:02.308 10230 10230 I MonoDroid: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
09-12 12:13:02.308 10230 10230 I MonoDroid: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
09-12 12:13:02.308 10230 10230 I MonoDroid: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2291)
09-12 12:13:02.308 10230 10230 I MonoDroid: 	at android.os.Handler.dispatchMessage(Handler.java:106)
09-12 12:13:02.308 10230 10230 I MonoDroid: 	at android.os.Looper.loopOnce(Looper.java:210)
09-12 12:13:02.308 10230 10230 I MonoDroid: 	at android.os.Looper.loop(Looper.java:299)
09-12 12:13:02.308 10230 10230 I MonoDroid: 	at android.app.ActivityThread.main(ActivityThread.java:8309)
09-12 12:13:02.308 10230 10230 I MonoDroid: 	at java.lang.reflect.Method.invoke(Native Method)
09-12 12:13:02.308 10230 10230 I MonoDroid: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
09-12 12:13:02.308 10230 10230 I MonoDroid: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1038)
09-12 12:13:02.308 10230 10230 I MonoDroid: Caused by: java.lang.ClassNotFoundException: com.google.android.vending.licensing.AESObfuscator
09-12 12:13:02.308 10230 10230 I MonoDroid: 	at crc648e5438a58262f792.SMainActivity.n_onCreate(Native Method)
09-12 12:13:02.308 10230 10230 I MonoDroid: 	at crc648e5438a58262f792.SMainActivity.onCreate(SMainActivity.java:31)
09-12 12:13:02.308 10230 10230 I MonoDroid: 	at android.app.Activity.performCreate(Activity.java:8176)
09-12 12:13:02.308 10230 10230 I MonoDroid: 	at android.app.Activity.performCreate(Activity.java:8143)
09-12 12:13:02.308 10230 10230 I MonoDroid: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1330)
09-12 12:13:02.308 10230 10230 I MonoDroid: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3744)
09-12 12:13:02.308 10230 10230 I MonoDroid: 	... 12 more
09-12 12:13:02.308 10230 10230 I MonoDroid: 
09-12 12:13:02.334 10230 10230 I Process : Sending signal. PID: 10230 SIG: 9</pre> #

**Comment by ElouJourney** [comment]
I have the same problem the android is launching the game but it just white screen and auto close itself.

**Comment by MossyBone** [comment]
same thing :( pls write if you manage to fix it

**Comment by lululoid** [comment]
> same thing :( pls write if you manage to fix it

I downgraded it to version 1.5.6.39 and it works

**Comment by MossyBone** [comment]
> > same thing :( pls write if you manage to fix it
> 
> I downgraded it to version 1.5.6.39 and it works

thank you! it does launch now, but mods aren't working. even preinstaled in SMAPI console commands and keyboard. ow.

**Comment by lululoid** [comment]
> > > same thing :( pls write if you manage to fix it
> > 
> > I downgraded it to version 1.5.6.39 and it works
> 
> thank you! it does launch now, but mods aren't working. even preinstaled in SMAPI console commands and keyboard. ow.

Maybe you put it in the wrong folder because I did that before putting it here 
 `/storage/emulated/0/Android/data/com.zane.stardewvalley/files/Mods`

**Comment by MossyBone** [comment]
> > > > same thing :( pls write if you manage to fix it
> > > 
> > > 
> > > I downgraded it to version 1.5.6.39 and it works
> > 
> > 
> > thank you! it does launch now, but mods aren't working. even preinstaled in SMAPI console commands and keyboard. ow.
> 
> Maybe you put it in the wrong folder because I did that before putting it here `/storage/emulated/0/Android/data/com.zane.stardewvalley/files/Mods`

i didn't have that folder. took plenty of time, but after some deleting and reinstallation it worked just fine! still don't know what was wrong exactly, but i'm glad it's resolved. thanks for advices!

**Comment by dotamidplayer** [comment]
dude, theres no 1.5.6.51 version and buy the app dont use the mod version :)

**Comment by ElouJourney** [comment]
@dotamidplayer then what is this?![Screenshot_20230921-173239.jpg](https://github.com/ZaneYork/SMAPI-Android-Installer/assets/73434110/df15ae78-af6f-441f-ac53-03635d67773e)

**Comment by ElouJourney** [comment]
> ![IMG_2175](https://github.com/ZaneYork/SMAPI-Android-Installer/assets/48650357/9d661b9e-6a02-43dc-9117-12e4a45ee664)
> ![IMG_2176](https://github.com/ZaneYork/SMAPI-Android-Installer/assets/48650357/5d1a2e62-7a4e-4935-88b3-46483beedf21)
> 

I see so the new update doesn't apply for some people I also bought the game so meh, idk what's with that

**Comment by lululoid** [comment]
> > ![IMG_2175](https://user-images.githubusercontent.com/48650357/269571686-9d661b9e-6a02-43dc-9117-12e4a45ee664.png)
> > ![IMG_2176](https://user-images.githubusercontent.com/48650357/269571752-5d1a2e62-7a4e-4935-88b3-46483beedf21.jpeg)
> 
> I see so the new update doesn't apply for some people I also bought the game so meh, idk what's with that

Is it working for you on 1.5.6.51?

**Comment by piostathicc** [comment]
> > same thing :( pls write if you manage to fix it
> 
> I downgraded it to version 1.5.6.39 and it works

Could you perhaps explain how to downgrade the game on Android?
