### ISSUE TITLE
Smapi message waiting and error when reinstalling

### ISSUE THREAD

**Issue by sabrininharc** [ZaneYork/SMAPI-Android-Installer#572]
I used to play Stardew Valley with mods but my phone updated and now when I play it keeps popping up all the time while waiting and this impacts the game. Then I went to reinstall Smapi and it didn't open, there was a white screen.

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.zane.stardewvalley/crc648e5438a58262f792.SMainActivity}: java.lang.ClassNotFoundException: com.google.android.vending.licensing.AESObfuscator
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3814)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3960)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2410)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8167)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)
Caused by: java.lang.ClassNotFoundException: com.google.android.vending.licensing.AESObfuscator
	at crc648e5438a58262f792.SMainActivity.n_onCreate(Native Method)
	at crc648e5438a58262f792.SMainActivity.onCreate(SMainActivity.java:31)
	at android.app.Activity.performCreate(Activity.java:8522)
	at android.app.Activity.performCreate(Activity.java:8486)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1437)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3795)
	... 12 more

**Comment by Zencee** [comment]
it's mostly because you're now using SDV 1.5.6.51 which is a new version and wouldn't work with the current smapi

**Comment by sabrininharc** [comment]
Wow, I didn't even realize I had updated. Thank you very much, so at the moment I have to go back to the previous version until Smapi is updated, right!

Thanks for the answer!
