### ISSUE TITLE
星露谷物语1.5.6.52 smapi patch后启动崩溃

### ISSUE THREAD

**Issue by dofes** [ZaneYork/SMAPI-Android-Installer#618]
崩溃日志
android.runtime.JavaProxyThrowable: System.NotSupportedException: Cannot create instance of type 'StardewValley.MainActivity+LicensingChecker': no Java peer type found.
  at Java.Interop.JniPeerMembers+JniInstanceMethods..ctor (System.Type declaringType) [0x0004b] in <ee6843d645da44b0965c1ea204d315bd>:0 
  at Java.Interop.JniPeerMembers+JniInstanceMethods.GetConstructorsForType (System.Type declaringType) [0x00031] in <ee6843d645da44b0965c1ea204d315bd>:0 
  at Java.Interop.JniPeerMembers+JniInstanceMethods.StartCreateInstance (System.String constructorSignature, System.Type declaringType, Java.Interop.JniArgumentValue* parameters) [0x00038] in <ee6843d645da44b0965c1ea204d315bd>:0 
  at Java.Lang.Object..ctor () [0x00034] in <8638e88f61db46e4bc35e66b77e3b3e8>:0 
  at StardewValley.MainActivity+LicensingChecker..ctor () [0x00000] in <a3055ff543b5460abe4e11e1b9d5f084>:0 
  at StardewValley.MainActivity.DoLicenseCheck () [0x0000a] in <a3055ff543b5460abe4e11e1b9d5f084>:0 
  at StardewValley.MainActivity.OnCreatePartTwo () [0x00053] in <a3055ff543b5460abe4e11e1b9d5f084>:0 
  at StardewValley.MainActivity.CheckAppPermissions () [0x00018] in <a3055ff543b5460abe4e11e1b9d5f084>:0 
  at StardewValley.MainActivity.OnCreate (Android.OS.Bundle bundle) [0x00063] in <a3055ff543b5460abe4e11e1b9d5f084>:0 
  at StardewModdingAPI.SMainActivity.OnCreate (Android.OS.Bundle bundle) [0x00170] in <a657c589ffdc433da6b7a1a6216be427>:0 
  at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState) [0x0000f] in <8638e88f61db46e4bc35e66b77e3b3e8>:0 
  at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPL_V (_JniMarshal_PPL_V callback, System.IntPtr jnienv, System.IntPtr klazz, System.IntPtr p0) [0x00005] in <8638e88f61db46e4bc35e66b77e3b3e8>:0 
	at crc648e5438a58262f792.SMainActivity.n_onCreate(Native Method)
	at crc648e5438a58262f792.SMainActivity.onCreate(SMainActivity.java:31)
	at android.app.Activity.performCreate(Activity.java:8241)
	at android.app.Activity.performCreate(Activity.java:8207)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3721)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3922)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2286)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8265)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)

**Comment by Adidds** [comment]
When will SMAPI Stardew Valley 1.5.6.52 be released on Android
